### PR TITLE
Resolve conflicts

### PR DESCRIPTION
**Pull request by martinDRD**

### CODE REVIEW

**Comment by rgcmme** [comment]
* The selfAssessment file is incomplete. Include all the items even if they are not checked.
* Remove your .DS_store files from the pull request.

**Comment by enzoferey** [comment]
Updated with HandsOn3 files and fixes from previous HandsOn.

**Comment by rgcmme** [comment]
* Some of the files are not in their proper directory.
* All the things that you have not checked in the self-assessment form must be corrected.

**Comment by enzoferey** [comment]
Actualizado con el feedback.

**Comment by enzoferey** [comment]
Added Assignments 6

**Pull request merged**
