### PR TITLE
Añadida la tarea de grupo 1

### PR DESCRIPTION
**Pull request by dguillen89**

### CODE REVIEW

**Comment by rgcmme** [comment]
There are 454 files in the pull request and I cannot see all the files without accepting the pull request.
The goal is not to include there all the files that you find, but only those that you will use in your hands-on.
If there are plenty of similar files (e.g., the trafficData* ones) just put them in a zip file.

**Comment by dguillen89** [comment]
Se han eliminado los ficheros .csv y se han añadido a un .zip

**Comment by rgcmme** [comment]
For the self-assessment, you have to use the template provided; what you have included in the file can be inserted in the "Comments" section, even if it is not compulsory.

**Comment by dguillen89** [comment]
Se ha modificado el fichero selfAssessmentHandsOn1 de acuerdo a la plantilla propuesta

**Comment by rgcmme** [comment]
The markdown format already allows to check the items:
* Yes: [x]
* No: [ ]

**Comment by dguillen89** [comment]
Se ha modificado el formato de las task lists para markdown

**Pull request merged**
